apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: monitoring
spec:
  storageClassName: local-storage
  volumeName: prometheus
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
