apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: monitoring
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/data/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - microlab-node-1
