apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  storageClassName: local-storage
  volumeName: grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
