apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
  namespace: monitoring
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/data/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - micro-node-1
