apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: monitoring
spec:
  storageClassName: local-storage
  volumeName: loki
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
